### ISSUE TITLE
enhance help/documentation

### ISSUE THREAD

**Issue by rthrd** [ppladdressbook/ppl#54]
being new to ppl I had a bit trouble to get it working:

1) ppl help produces only the commands.
     -  would be nice to add an line like
        `help for commands with ppl <command> --help`
     -  would be wonderfull to support sub-commands for help,
        so that `ppl help command` would show command's help
        and not only the general help
2) documentation in the gem is missing
    -  would be nice to have the content of http://ppladdressbook.org/documentation
        in the gem

Thank you for this wonderfull tool!

**Comment by hnrysmth** [comment]
Hey there @rthrd 

Can't really apologise enough for the slow response on this. I had to turn of GitHub notifications a while ago because they were out of hand and a lot of things have slipped by as a result. If you're still interested, I'd be happy to add you as a collaborator to the project so that you can improve the documentation. Interested?

**Comment by hnrysmth** [comment]
Been thinking about this and I definitely like the idea. I'd be really happy to see a PR implementing it. But I'm not gonna do it myself so will close this issue in the mean time.
