### ISSUE TITLE
ppl post --interactive

### ISSUE THREAD

**Issue by sharethewisdom** [ppladdressbook/ppl#57]
When adding a postal address, I frequently consult the help because I'm bad at remembering the flags for the one-liner. 

It would be more convenient if adding a new address could be made more interactive with unescaped and unquoted input. Ultimately, this could also allow default values to be configured.

example:

    $ ppl post -i
    > add address for which contact? alice
    contact found.
    > type or id: work
    another address is found.
    > set preferred? (y/n/s) s
    skipped.
    > country (default US):
    United States
    > region (default New York):
    New York
    > locality (village/city): Newark
    > postal (zip) code: 14513
    > street name: Somestreet st. Whatnot
    > number: 513
    successfully added work address for alice
    > exit or add? (e/a)

thanks for the great program, I'm looking forward to hear what you think,
Bart

**Comment by hnrysmth** [comment]
Yep, I've never enjoyed using that command myself either. You're right that an interactive mode would help, and `ppl post -i` seems like a lovely place for it to live.

If somebody submitted a PR implementing this I'd gladly work with them to get it merged. But since I'm unlikely to find the time to do this myself I'm going to close this issue for now.
